/**
 * The **craft** DSA5 talent group (*Handwerkstalente*) as mechanical roster entries — one `Talent` per
 * skill, carrying only the boundary-permitted data (name via i18n key + attribute triple + category +
 * improvement cost + encumbrance + application-name slugs; **no** descriptions/flavour/values). Sourced
 * from the official English *The Dark Eye* Regel-Wiki (<https://tde.ulisses-regelwiki.de/craft-skills.html>).
 *
 * **Fidelity SSOT (ADR 0029):** verified against the owner's DSA5 vault — each entry carries its own
 * `regelwiki` id (public, normative) + `vaultNote` path (private anchor), so its mechanics can be
 * re-checked against the authority instead of trusted. Pointers only; no rule text is copied here.
 *
 * Kept as plain data (see `types.ts`): the SDK `TraitDefinition`/`CheckDefinition` are *derived* from
 * these entries (`skills.ts` / `checks.ts`), so the DSA5-specific fields live here in the plugin while
 * the core stays rule-agnostic (ADR 0020).
 */

import type { Talent } from './types';

/**
 * The 17 craft-group DSA5 talents. Exists so the DSA5 plugin can build its skill/check catalog from a
 * single mechanical source of truth without embedding any copyrighted rule text (content boundary:
 * `docs/legal/dsa5-content-boundary.md`). Order follows the Regel-Wiki's alphabetical listing.
 */
export const CRAFT_TALENTS: readonly Talent[] = [
  {
    id: 'ALCHEMY',
    checkId: 'alchemy',
    labelKey: 'dsa5.skill.alchemy',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Alchimie',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Alchimie.md',
    attributeIds: ['COU', 'SGC', 'DEX'],
    category: 'craft',
    improvementCost: 'C',
    encumbrance: 'yes',
    applications: ['alchemical-poisons', 'elixirs', 'mundane-alchemy'],
  },
  {
    id: 'ARTISTIC_ABILITY',
    checkId: 'artistic-ability',
    labelKey: 'dsa5.skill.artisticAbility',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Malen+%26+Zeichnen',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Malen & Zeichnen.md',
    attributeIds: ['INT', 'DEX', 'DEX'],
    category: 'craft',
    improvementCost: 'A',
    encumbrance: 'yes',
    applications: ['carving', 'drawing', 'painting'],
  },
  {
    id: 'CLOTHWORKING',
    checkId: 'clothworking',
    labelKey: 'dsa5.skill.clothworking',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Stoffbearbeitung',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Stoffbearbeitung.md',
    attributeIds: ['SGC', 'DEX', 'DEX'],
    category: 'craft',
    improvementCost: 'A',
    encumbrance: 'yes',
    applications: ['dyeing', 'felting', 'sewing', 'weaving', 'spinning'],
  },
  {
    id: 'COMMERCE',
    checkId: 'commerce',
    labelKey: 'dsa5.skill.commerce',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Handel',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Handel.md',
    attributeIds: ['SGC', 'INT', 'CHA'],
    category: 'craft',
    improvementCost: 'B',
    encumbrance: 'no',
    applications: ['accounting', 'haggling', 'money-exchange'],
  },
  {
    id: 'DRIVING',
    checkId: 'driving',
    labelKey: 'dsa5.skill.driving',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Fahrzeuge',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Fahrzeuge.md',
    attributeIds: ['CHA', 'DEX', 'CON'],
    category: 'craft',
    improvementCost: 'A',
    encumbrance: 'yes',
    applications: ['chases', 'combat-maneuvers', 'long-distances', 'races'],
  },
  {
    id: 'EARTHENCRAFT',
    checkId: 'earthencraft',
    labelKey: 'dsa5.skill.earthencraft',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Steinbearbeitung',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Steinbearbeitung.md',
    attributeIds: ['DEX', 'DEX', 'STR'],
    category: 'craft',
    improvementCost: 'A',
    encumbrance: 'yes',
    applications: ['stonecutting', 'masonry', 'stone-carving'],
  },
  {
    id: 'LEATHERWORKING',
    checkId: 'leatherworking',
    labelKey: 'dsa5.skill.leatherworking',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Lederbearbeitung',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Lederbearbeitung.md',
    attributeIds: ['DEX', 'AGI', 'CON'],
    category: 'craft',
    improvementCost: 'B',
    encumbrance: 'yes',
    applications: ['furrier', 'produce-leather-goods', 'tanning'],
  },
  {
    id: 'METALWORKING',
    checkId: 'metalworking',
    labelKey: 'dsa5.skill.metalworking',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Metallbearbeitung',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Metallbearbeitung.md',
    attributeIds: ['DEX', 'CON', 'STR'],
    category: 'craft',
    improvementCost: 'C',
    encumbrance: 'yes',
    applications: ['blacksmith', 'casting', 'goldsmith', 'smelting'],
  },
  {
    id: 'MUSIC',
    checkId: 'music',
    labelKey: 'dsa5.skill.music',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Musizieren',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Musizieren.md',
    attributeIds: ['CHA', 'DEX', 'CON'],
    category: 'craft',
    improvementCost: 'A',
    encumbrance: 'yes',
    applications: ['drums', 'string-instruments', 'wind-instruments'],
  },
  {
    id: 'PICK_LOCKS',
    checkId: 'pick-locks',
    labelKey: 'dsa5.skill.pickLocks',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Schl%C3%B6sserknacken',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Schlösserknacken.md',
    attributeIds: ['INT', 'DEX', 'DEX'],
    category: 'craft',
    improvementCost: 'C',
    encumbrance: 'yes',
    applications: ['bit-locks', 'combination-locks'],
  },
  {
    id: 'PREPARE_FOOD',
    checkId: 'prepare-food',
    labelKey: 'dsa5.skill.prepareFood',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Lebensmittelbearbeitung',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Lebensmittelbearbeitung.md',
    attributeIds: ['INT', 'DEX', 'DEX'],
    category: 'craft',
    improvementCost: 'A',
    encumbrance: 'yes',
    applications: ['baking', 'brewing', 'frying-and-boiling', 'gutting', 'preserving'],
  },
  {
    id: 'SAILING',
    checkId: 'sailing',
    labelKey: 'dsa5.skill.sailing',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Boote+%26+Schiffe',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Boote & Schiffe.md',
    attributeIds: ['DEX', 'AGI', 'STR'],
    category: 'craft',
    improvementCost: 'B',
    encumbrance: 'yes',
    applications: ['chases', 'combat-maneuvers', 'long-distances', 'races'],
  },
  {
    id: 'TREAT_DISEASE',
    checkId: 'treat-disease',
    labelKey: 'dsa5.skill.treatDisease',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Heilkunde+Krankheiten',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Heilkunde Krankheiten.md',
    attributeIds: ['COU', 'INT', 'CON'],
    category: 'craft',
    improvementCost: 'B',
    encumbrance: 'yes',
    applications: ['individual-diseases'],
  },
  {
    id: 'TREAT_POISON',
    checkId: 'treat-poison',
    labelKey: 'dsa5.skill.treatPoison',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Heilkunde+Gift',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Heilkunde Gift.md',
    attributeIds: ['COU', 'SGC', 'INT'],
    category: 'craft',
    improvementCost: 'B',
    encumbrance: 'yes',
    applications: ['alchemical-poisons', 'mineral-based-poisons', 'plant-based-toxins', 'venoms'],
  },
  {
    id: 'TREAT_SOUL',
    checkId: 'treat-soul',
    labelKey: 'dsa5.skill.treatSoul',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Heilkunde+Seele',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Heilkunde Seele.md',
    attributeIds: ['INT', 'CHA', 'CON'],
    category: 'craft',
    improvementCost: 'B',
    encumbrance: 'no',
    applications: ['suppress-negative-trait', 'suppress-fear', 'suppress-personality-flaw'],
  },
  {
    id: 'TREAT_WOUNDS',
    checkId: 'treat-wounds',
    labelKey: 'dsa5.skill.treatWounds',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Heilkunde+Wunden',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Heilkunde Wunden.md',
    attributeIds: ['SGC', 'DEX', 'DEX'],
    category: 'craft',
    improvementCost: 'D',
    encumbrance: 'yes',
    applications: ['enhance-healing', 'relieve-pain', 'stabilize'],
  },
  {
    id: 'WOODWORKING',
    checkId: 'woodworking',
    labelKey: 'dsa5.skill.woodworking',
    regelwiki: 'https://dsa.ulisses-regelwiki.de/talent.html?talent=Holzbearbeitung',
    vaultNote: '01 Regeln/Talente/Handwerkstalente/Holzbearbeitung.md',
    attributeIds: ['DEX', 'AGI', 'STR'],
    category: 'craft',
    improvementCost: 'B',
    encumbrance: 'yes',
    applications: ['carpenter', 'felling-and-cutting', 'joiner'],
  },
];
